spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/development
    username: root
    password: GAtech321
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
#  security:
#    user:
#      name: admin
#      password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: test.piot.315@gmail.com
    password: GAtech321
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
